export const DEFAULTS = {
  SCREENSHOT_INTERVAL_MIN: 5,
  IDLE_TIMEOUT_MIN: 5,
  ACTIVITY_SYNC_INTERVAL_SEC: 60,
  RANDOM_SCREENSHOT_WINDOW_MIN: 5,
  JWT_ACCESS_EXPIRY: "15m",
  JWT_REFRESH_EXPIRY: "7d",
  SCREENSHOT_QUALITY: 75,
  MAX_OFFLINE_QUEUE_SIZE: 1000,
  DATA_RETENTION_DAYS: 90,
  BUDGET_ALERT_THRESHOLD_PCT: 80,
} as const;

export const ACTIVITY_THRESHOLDS = {
  LOW: 30,
  MEDIUM: 60,
  HIGH: 80,
} as const;

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 25,
  MAX_LIMIT: 100,
} as const;
